data_path: ../data/dataset.yaml
conf_file: ../configs/yolov6s.py
img_size: 640
batch_size: 8
epochs: 10
workers: 8
device: '0'
eval_interval: 20
eval_final_only: true
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: ./runs/train
name: exp
dist_url: env://
gpu_count: 0
local_rank: -1
resume: null
rank: -1
world_size: 1
save_dir: runs/train/exp
